AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    media-release-notifier

    Sample SAM Template for media-release-notifier

Globals:
    Function:
        Timeout: 3

Parameters:
    ApiKey:
        Type: String
        Description: API Key
        Default: 'test'

Resources:
    ApiCallFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/handlers/apiCall
            Handler: apiCall.lambdaHandler
            Runtime: nodejs18.x
            Environment:
                Variables:
                    API_KEY: !Ref ApiKey
            Architectures:
                - x86_64
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /apiCall
                        Method: get
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                Sourcemap: true
                EntryPoints:
                    - apiCall.ts

Outputs:
    HelloWorldApi:
        Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
    ApiCallFunction:
        Description: 'ApiCall Lambda Function ARN'
        Value: !GetAtt ApiCallFunction.Arn
    ApiCallFunctionIamRole:
        Description: 'Implicit IAM Role created for Api Call function'
        Value: !GetAtt ApiCallFunctionRole.Arn
