AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    media-release-notifier

    Get email notifications for new media releases based on the genres you select.

Globals:
    Function:
        Timeout: 3

Parameters:
    ApiKey:
        Type: String
        Description: API Key
        Default: 'test'
    SesArn:
        Type: String
        Description: SES ARN
        Default: 'test'
    UserTable:
        Type: String
        Description: DynamoDB Table Name
        Default: 'UserTable'

Resources:
    DynamoDBTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            TableName: !Ref UserTable

    GetUpcomingMoviesFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/handlers/getUpcomingMovies
            Handler: getUpcomingMovies.lambdaHandler
            Runtime: nodejs18.x
            Environment:
                Variables:
                    API_KEY: !Ref ApiKey
                    SES_ARN: !Ref SesArn
            Policies:
                - SESCrudPolicy:
                      IdentityName: !Ref SesArn
            Architectures:
                - x86_64
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /getUpcomingMovies
                        Method: get
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                Sourcemap: true
                EntryPoints:
                    - getUpcomingMovies.ts

Outputs:
    HelloWorldApi:
        Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
    ApiCallFunction:
        Description: 'ApiCall Lambda Function ARN'
        Value: !GetAtt GetUpcomingMoviesFunction.Arn
    ApiCallFunctionIamRole:
        Description: 'Implicit IAM Role created for Api Call function'
        Value: !GetAtt GetUpcomingMoviesFunction.Arn
